esphome:
  name: hru400

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  manual_ip:
    static_ip: 192.168.1.30
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  power_save_mode: high

uart:
  id: mod_uart
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 128

modbus:
  send_wait_time: 200ms
  uart_id: mod_uart
  id: mod_bus

modbus_controller:
- id: modbus_hru400
  modbus_id: mod_bus
  address: 72   ## address of the Modbus slave device on the bus
  setup_priority: -10
  update_interval: 10s

sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Indoor Temperature"
  register_type: holding
  address: 3072   ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: "temperature"
  state_class: "measurement"
  value_type: S_WORD
  filters:
   - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Indoor Humidity"
  register_type: holding
  address: 3073  ## address of the register inside the Modbus slave device
  unit_of_measurement: "%"
  device_class: "humidity"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Power Intake Fan"
  register_type: holding
  address: 3022  ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Power Exhaust Fan"
  register_type: holding
  address: 3023  ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Volumestroom Naar Binnen"
  register_type: holding
  address: 3060  ## address of the register inside the Modbus slave device
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Volumestroom Naar Buiten"
  register_type: holding
  address: 3080  ## address of the register inside the Modbus slave device
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  value_type: U_WORD