esphome:
  name: hru400

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
- platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  manual_ip:
    static_ip: 192.168.1.30
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  power_save_mode: high

uart:
  id: mod_uart
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 128

modbus:
  send_wait_time: 200ms
  uart_id: mod_uart
  id: mod_bus

modbus_controller:
- id: modbus_hru400
  modbus_id: mod_bus
  address: 72   ## address of the Modbus slave device on the bus
  setup_priority: -10
  update_interval: 10s

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Snelheid toevoerventilator"
    register_type: holding
    address: 3020
    unit_of_measurement: "rpm"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Snelheid afvoerventilator"
    register_type: holding
    address: 3021
    unit_of_measurement: "rpm"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Vermogen toevoerventilator"
    register_type: holding
    address: 3022
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Vermogen afvoerventilator"
    register_type: holding
    address: 3023
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    value_type: U_WORD

#
# Sensor van buitenaf
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom van buitenaf"
    register_type: holding
    address: 3030
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Massastroom van buitenaf"
    register_type: holding
    address: 3031
    unit_of_measurement: "kg/h"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Temperatuur van buitenaf"
    register_type: holding
    address: 3032
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    value_type: S_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Luchtvochtigheid van buitenaf"
    register_type: holding
    address: 3033
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    value_type: U_WORD
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom vorstklep"
    register_type: holding
    address: 3040
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

#
# Sensor gemengd
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom gemengd"
    register_type: holding
    address: 3050
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Massastroom gemengd"
    register_type: holding
    address: 3051
    unit_of_measurement: "kg/h"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Temperatuur gemengd"
    register_type: holding
    address: 3052
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    value_type: S_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Luchtvochtigheid gemengd"
    register_type: holding
    address: 3053
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    value_type: U_WORD

#
# Sensor naar gebouw
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom naar gebouw"
    register_type: holding
    address: 3060
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Massastroom naar gebouw"
    register_type: holding
    address: 3061
    unit_of_measurement: "kg/h"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Temperatuur naar gebouw"
    register_type: holding
    address: 3062
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    value_type: S_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Luchtvochtigheid naar gebouw"
    register_type: holding
    address: 3063
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    value_type: U_WORD

#
# Sensor van gebouw
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom van gebouw"
    register_type: holding
    address: 3070
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Massastroom van gebouw"
    register_type: holding
    address: 3071
    unit_of_measurement: "kg/h"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Temperatuur van gebouw"
    register_type: holding
    address: 3072
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    value_type: S_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Luchtvochtigheid van gebouw"
    register_type: holding
    address: 3073
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    value_type: U_WORD

#
# Sensor naar buiten
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Volumestroom naar buiten"
    register_type: holding
    address: 3080
    unit_of_measurement: "m³/h"
    device_class: "volume_flow_rate"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Massastroom naar buiten"
    register_type: holding
    address: 3081
    unit_of_measurement: "kg/h"
    state_class: "measurement"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Temperatuur naar buiten"
    register_type: holding
    address: 3082
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    value_type: S_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Luchtvochtigheid naar buiten"
    register_type: holding
    address: 3083
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    value_type: U_WORD

#
# Error signaal
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Foutnummer"
    register_type: holding
    address: 199
    state_class: "measurement"
    value_type: U_WORD

number:
#
# Besturing van de ventilator
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Ventilatievraag"
    id: HRU_ventilatievraag
    min_value: 0
    max_value: 399
    step: 1
    register_type: holding
    address: 2010
    value_type: U_WORD
    use_write_multiple: true
    on_value_range:
      - above: 2.0
        then: 
          - number.set:
              id: HRU_ventilatievraag_aan_uit
              value: 1.0
      - below: 1.0
        then:
          - number.set:
              id: HRU_ventilatievraag_aan_uit
              value: 0.0

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Ventilatievraag - aan/uit"
    id: HRU_ventilatievraag_aan_uit
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    address: 2011
    value_type: U_WORD
    use_write_multiple: true

#
# Besturing vorstklep
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Vorstklep positie"
    id: HRU_positie_vorstklep
    min_value: 0
    max_value: 510
    step: 1
    register_type: holding
    address: 2030
    value_type: U_WORD
    use_write_multiple: true
    on_value_range:
      - above: 2.0
        then: 
          - number.set:
              id: HRU_vorstklep_aan_uit
              value: 1.0
      - below: 1.0
        then:
          - number.set:
              id: HRU_vorstklep_aan_uit
              value: 0.0

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Vorstklep - aan/uit"
    id: HRU_vorstklep_aan_uit
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    address: 2031
    value_type: U_WORD
    use_write_multiple: true

#
# Besturing bypass klep
#
  # Inside air is directed to outside without passing the heat ex changer
  # Thus cold outside air does not heat up from the hot inside air
  # Note from manufacturer: 
     # Als u via MobBus RS-485 de bypassklep open wil zetten dient u 
     # de afvoerventilator af te laten toeren naar 200 m³/h of minder.
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "Bypass klep - aan/uit"
    id: HRU_bypass_klep_aan_uit
    min_value: 0
    max_value: 1
    step: 1
    register_type: holding
    address: 2033
    value_type: U_WORD
    use_write_multiple: true
    icon: mdi:home-import-outline

#
# Foutcodes
#
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[01] Filter vuil (volumemeting)"
    id: HRU_errors01
    register_type: holding
    address: 200
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[02] Filter vuil (tijdmeting)"
    id: HRU_errors02
    register_type: holding
    address: 201
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[03] Flow-waarschuwing afvoervolume"
    id: HRU_errors03
    register_type: holding
    address: 202
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[04] Flow-waarschuwing toevoervolume"
    id: HRU_errors04
    register_type: holding
    address: 203
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[11] Fout vochtsensor intern"
    id: HRU_errors11
    register_type: holding
    address: 210
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[12] Fout vochtsensor afvoer"
    id: HRU_errors12
    register_type: holding
    address: 211
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[13] Fout vochtsensor toevoer"
    id: HRU_errors13
    register_type: holding
    address: 212
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[14] Fout temperatuursensor intern"
    id: HRU_errors14
    register_type: holding
    address: 213
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[15] Fout temperatuursensor afvoer"
    id: HRU_errors15
    register_type: holding
    address: 214
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[16] Fout vochtsensor afvoer"
    id: HRU_errors16
    register_type: holding
    address: 215
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[17] Fout klep zone 1"
    id: HRU_errors17
    register_type: holding
    address: 216
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[18] Fout klep zone 2"
    id: HRU_errors18
    register_type: holding
    address: 217
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[19] Fout klep zone 3"
    id: HRU_errors19
    register_type: holding
    address: 218
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[20] Fout klep zone 4"
    id: HRU_errors20
    register_type: holding
    address: 219
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[21] Fout bypassklep"
    id: HRU_errors21
    register_type: holding
    address: 220
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[22] Fout vorstklep"
    id: HRU_errors22
    register_type: holding
    address: 221
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[23] Fout elektronicacompartiment"
    id: HRU_errors23
    register_type: holding
    address: 222
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[31] Fout volumesensor afvoer"
    id: HRU_errors31
    register_type: holding
    address: 230
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[32] Fout volumesensor toevoer"
    id: HRU_errors32
    register_type: holding
    address: 231
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[33] Fout ventilatormodule afvoer"
    id: HRU_errors33
    register_type: holding
    address: 232
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[34] Fout ventilatormodule toevoer"
    id: HRU_errors34
    register_type: holding
    address: 233
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true