esphome:
  name: hru400

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  manual_ip:
    static_ip: 192.168.1.30
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  power_save_mode: high

uart:
  id: mod_uart
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 128

modbus:
  send_wait_time: 200ms
  uart_id: mod_uart
  id: mod_bus

modbus_controller:
- id: modbus_hru400
  modbus_id: mod_bus
  address: 72   ## address of the Modbus slave device on the bus
  setup_priority: -10
  update_interval: 10s

sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Indoor Temperature"
  register_type: holding
  address: 3072   ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  device_class: "temperature"
  state_class: "measurement"
  value_type: S_WORD
  filters:
   - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Indoor Humidity"
  register_type: holding
  address: 3073  ## address of the register inside the Modbus slave device
  unit_of_measurement: "%"
  device_class: "humidity"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Power Intake Fan"
  register_type: holding
  address: 3022  ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Power Exhaust Fan"
  register_type: holding
  address: 3023  ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"
  device_class: "power"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Volumestroom Naar Binnen"
  register_type: holding
  address: 3060  ## address of the register inside the Modbus slave device
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Volumestroom Naar Buiten"
  register_type: holding
  address: 3080  ## address of the register inside the Modbus slave device
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
  state_class: "measurement"
  value_type: U_WORD

  - platform: modbus_controller
  modbus_controller_id: modbus_hru400
  name: "Foutnummer"
  register_type: holding
  address: 199
  state_class: "measurement"
  value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[1] Filter vuil (volumemeting)"
    id: HRU_errors1
    register_type: holding
    address: 200
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[2] Filter vuil (tijdmeting)"
    id: HRU_errors2
    register_type: holding
    address: 201
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[3] Flow-waarschuwing afvoervolume"
    id: HRU_errors3
    register_type: holding
    address: 202
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[4] Flow-waarschuwing toevoervolume"
    id: HRU_errors4
    register_type: holding
    address: 203
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[11] Fout vochtsensor intern"
    id: HRU_errors11
    register_type: holding
    address: 210
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[12] Fout vochtsensor afvoer"
    id: HRU_errors12
    register_type: holding
    address: 211
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[13] Fout vochtsensor toevoer"
    id: HRU_errors13
    register_type: holding
    address: 212
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[14] Fout temperatuursensor intern"
    id: HRU_errors14
    register_type: holding
    address: 213
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[15] Fout temperatuursensor afvoer"
    id: HRU_errors15
    register_type: holding
    address: 214
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[16] Fout vochtsensor afvoer"
    id: HRU_errors16
    register_type: holding
    address: 215
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[17] Fout klep zone 1"
    id: HRU_errors17
    register_type: holding
    address: 216
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[18] Fout klep zone 2"
    id: HRU_errors18
    register_type: holding
    address: 217
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[19] Fout klep zone 3"
    id: HRU_errors19
    register_type: holding
    address: 218
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true

  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[20] Fout klep zone 4"
    id: HRU_errors20
    register_type: holding
    address: 219
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[21] Fout bypassklep"
    id: HRU_errors21
    register_type: holding
    address: 220
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[22] Fout vorstklep"
    id: HRU_errors22
    register_type: holding
    address: 221
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[23] Fout elektronicacompartiment"
    id: HRU_errors23
    register_type: holding
    address: 222
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[31] Fout volumesensor afvoer"
    id: HRU_errors31
    register_type: holding
    address: 230
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[32] Fout volumesensor toevoer"
    id: HRU_errors32
    register_type: holding
    address: 231
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[33] Fout ventilatormodule afvoer"
    id: HRU_errors33
    register_type: holding
    address: 232
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    
  - platform: modbus_controller
    modbus_controller_id: modbus_hru400
    name: "[34] Fout ventilatormodule toevoer"
    id: HRU_errors34
    register_type: holding
    address: 233
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true